# Generated by Django 3.1.5 on 2021-01-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_scrap', '0002_remove_content_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=1000, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='topic_images')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_scrap.content')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
