# Generated by Django 3.1.5 on 2021-01-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scrap', '0003_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
