# Generated by Django 3.1.5 on 2021-01-14 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_scrap', '0005_auto_20210114_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='content',
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='data',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_scrap.category'),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
