# Generated by Django 3.1.5 on 2021-01-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scrap', '0006_auto_20210114_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='suscribe',
            field=models.BooleanField(default=False),
        ),
    ]
